feat: #265 upgrade librairies, remove useless config and use managed one
Ferlab-Ste-Justine/cqdg-docs pull request #56
Opened 2021-03-15 20:06 UTC by kjacqueschu

2021-03-15 20:14 UTC, plaplante-chust requested changes

2021-03-15 20:14 UTC, plaplante-chust commented on README.md
>  # ICGC-ARGO Doc Site
ICGC ARGO

2021-03-15 20:14 UTC, plaplante-chust commented on website/algolia-doc-search.json
> +      "https://docs.qa.cqdg.ferlab.bio/en/submission/submitting-clinical-data/"
Est-ce possible d'avoir une conf par environnement? (QA, Prod)

2021-03-15 20:14 UTC, plaplante-chust commented on website/src/theme/Utils/translation.js
> +    console.log('translation context', context);
console.log

2021-03-15 20:14 UTC, plaplante-chust commented on website/src/theme/Utils/translation.js
> +
console.log

2021-03-15 20:14 UTC, plaplante-chust commented on website/src/theme/Navbar/index.js
> +                            console.log('link generation', link.href)
console.log

2021-03-15 20:53 UTC, kjacqueschu commented on website/algolia-doc-search.json
> +      "https://docs.qa.cqdg.ferlab.bio/en/submission/submitting-clinical-data/"
C'est pour rouler le crawler logiquement je le roulerais avec la config que je veux en production pour remplir les indices

2021-03-15 21:04 UTC, plaplante-chust submitted a review, later dismissed

2021-03-16 14:22 UTC, plaplante-chust approved these changes

2021-03-16 14:22 UTC, merged